### PR TITLE
fix(Persistence/Contexts): Fixed SaveChangeAsync method

### PR DESCRIPTION
**Pull request by uluserdar**
If the EntityState state was other than Modified or Added, it was throwing an error. I fixed it by checking in other cases

### CODE REVIEW

**Comment by GormYa** [comment]
The issue is that the switch does not provide a default value. As a result, the solution has an option that returns a default value, as shown below. It can be found here as additional information.

`_ = data.State switch
{
    EntityState.Added => data.Entity.CreatedDate = DateTime.UtcNow,
    EntityState.Modified => data.Entity.UpdatedDate = DateTime.UtcNow,
    _ => DateTime.UtcNow
};`

**Comment by GormYa** [comment]
The issue is that the switch does not provide a default value. As a result, the solution has an option that returns a default value, as shown below. It can be found here as additional information.

_ = data.State switch
{
    EntityState.Added => data.Entity.CreatedDate = DateTime.UtcNow,
    EntityState.Modified => data.Entity.UpdatedDate = DateTime.UtcNow,
    `_ => data.Entity.UpdatedDate = DateTime.UtcNow`
};

OR (alternative I haven't tried)

_ = data.State switch
{
    EntityState.Added => data.Entity.CreatedDate = DateTime.UtcNow,
    EntityState.Modified => data.Entity.UpdatedDate = DateTime.UtcNow,
    `_ => null`
};

**Comment by uluserdar** [comment]
Thank you for this information. 
It may not be correct to change the UpdatedDate property when the EntityState.Unchanged case occurs.

It may be the code below, but I haven't tried it myself.
_ = data.State switch
{
EntityState.Added => data.Entity.CreatedDate = DateTime.UtcNow,
EntityState.Modified => data.Entity.UpdatedDate = DateTime.UtcNow,
_ => null
};

**Comment by ahmet-cetinkaya** [comment]
#73

**Comment by uluserdar** [comment]
I'm closing this pull request. #79 has been merged. This fixes the problem and looks good
@ahmet-cetinkaya

**Pull request closed without merging**
