### PR TITLE
feat(core.persistence): repository registrations with reflection

### PR DESCRIPTION
**Pull request by yusuf-cirak**
Repository registrations can be made with reflection.

**AddRepositoryServices** method will search for classes specified in given **assembly** and given **genericType** parameters. After that your repositories will be added with Scoped life time to IoC container respectively.

### CODE REVIEW

**Comment by ahmet-cetinkaya** [comment]
How to change dependencies when we use another ORM instead of Entity framework?

**Comment by EmreAka** [comment]
Isn't this project designed to not change EF CORE? As I remember from Advance C# Boot-camp, Engin Demirog told that?

**Comment by yusuf-cirak** [comment]
> How to change dependencies when we use another ORM instead of Entity framework?

- The project itself has a dependency on EntityFramework so I didn't think about that.

**Comment by ahmet-cetinkaya** [comment]
The project does not have any dependencies on the EF Core library. In the application layer, we use a repository interface that got with dependency injection.

What you're talking about is that the Entity Framework library is now integrated with dotnet and doesn't need separate names, for example EfBrandRepository, and folders, for example src/rentACar/Persistence/Repositories/EntityFramework. Still, dependencies should be changed based on preferences.

**Pull request closed without merging**
